name: FreeDNS Registry Data Publisher

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour
  workflow_dispatch: # Allows manual triggering

jobs:
  scrape_and_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to create releases and tags

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml
          sudo apt-get update && sudo apt-get install -y brotli # Install brotli CLI tool

      - name: Run parser script
        id: parser
        run: python parser.py # This should generate fraidex.json (indented)

      - name: Check if fraidex.json was generated
        id: check_json
        run: |
          if [ -f fraidex.json ]; then
            echo "Generated fraidex.json found."
            echo "exists=true" >> $GITHUB_OUTPUT
            if [ -s fraidex.json ]; then
              echo "has_content=true" >> $GITHUB_OUTPUT
            else
              echo "has_content=false" >> $GITHUB_OUTPUT
              echo "Warning: fraidex.json is empty."
            fi
          else
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "Error: fraidex.json not found after running parser.py!"
            exit 1
          fi

      - name: Create minified JSON version
        if: steps.check_json.outputs.exists == 'true' && steps.check_json.outputs.has_content == 'true'
        run: |
          python -m json.tool fraidex.json fraidex.min.json --no-indent
          echo "Created fraidex.min.json"

      - name: Check if fraidex.min.json was generated
        if: steps.check_json.outputs.exists == 'true' && steps.check_json.outputs.has_content == 'true'
        id: check_min_json
        run: |
          if [ -f fraidex.min.json ]; then
            echo "Generated fraidex.min.json found."
            echo "exists=true" >> $GITHUB_OUTPUT
            if [ -s fraidex.min.json ]; then
              echo "has_content=true" >> $GITHUB_OUTPUT
            else
              echo "has_content=false" >> $GITHUB_OUTPUT
              echo "Warning: fraidex.min.json is empty after minification."
            fi
          else
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "Error: fraidex.min.json not found after minification step!"
            exit 1
          fi

      - name: Create compressed versions (Gzip and Brotli)
        if: steps.check_min_json.outputs.exists == 'true' && steps.check_min_json.outputs.has_content == 'true'
        run: |
          echo "Compressing fraidex.min.json..."
          gzip -k -f -9 fraidex.min.json # -k (keep original), -f (force), -9 (best compression) -> fraidex.min.json.gz
          brotli -k -f -Z fraidex.min.json # -k (keep original), -f (force), -Z (best quality) -> fraidex.min.json.br
          echo "Created fraidex.min.json.gz and fraidex.min.json.br"

      - name: Check if compressed files were generated
        if: steps.check_min_json.outputs.exists == 'true' && steps.check_min_json.outputs.has_content == 'true' # Relies on min_json check
        id: check_compressed_files
        run: |
          gz_exists=false
          br_exists=false
          if [ -f fraidex.min.json.gz ] && [ -s fraidex.min.json.gz ]; then
            gz_exists=true
            echo "Generated fraidex.min.json.gz found and has content."
          else
            echo "Error or empty: fraidex.min.json.gz not found or is empty after compression!"
          fi
          if [ -f fraidex.min.json.br ] && [ -s fraidex.min.json.br ]; then
            br_exists=true
            echo "Generated fraidex.min.json.br found and has content."
          else
            echo "Error or empty: fraidex.min.json.br not found or is empty after compression!"
          fi
          if [ "$gz_exists" = true ] && [ "$br_exists" = true ]; then
            echo "all_compressed_exist=true" >> $GITHUB_OUTPUT
          else
            echo "all_compressed_exist=false" >> $GITHUB_OUTPUT
            exit 1 # Fail if compressed files are missing/empty
          fi

      - name: Set current time for release body
        if: steps.check_compressed_files.outputs.all_compressed_exist == 'true'
        id: current_time
        run: echo "time=$(date -u +'%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_OUTPUT

      - name: Delete previous data-latest release and tag
        if: steps.check_compressed_files.outputs.all_compressed_exist == 'true'
        run: |
          echo "Attempting to delete previous 'data-latest' release and tag..."
          gh release delete data-latest -y --cleanup-tag || echo "No previous 'data-latest' release or tag to delete, or deletion failed (which is fine if it didn't exist)."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release and Upload Assets
        if: steps.check_compressed_files.outputs.all_compressed_exist == 'true'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            fraidex.json
            fraidex.min.json
            fraidex.min.json.gz
            fraidex.min.json.br
          tag_name: data-latest
          name: "Latest FreeDNS Data"
          body: |
            Latest FreeDNS domain registry data.
            - `fraidex.json`: Human-readable, indented version.
            - `fraidex.min.json`: Minified version.
            - `fraidex.min.json.gz`: Gzip compressed minified version.
            - `fraidex.min.json.br`: Brotli compressed minified version.
            Updated: ${{ steps.current_time.outputs.time }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
